name: Build and Test CI

on: [ push, pull_request ]

jobs:
  build:
    name: Gradle Build
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Setup Gradle with cache
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Gradle
        run: chmod +x gradlew

      - name: Gradle build
        run: bash ./gradlew assembleDebug

      - name: Run kltlint
        run: ./gradlew ktlintCheck

      - name: Unit tests
        run: ./gradlew test --stacktrace

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: AppUpdateChecker/build/reports